name: CommandSpy
main: me.maxed.cspy.CSpy
description: "Adds to your server Command-Spy system"
version: 1.1
api-version: 1.16
softdepend: [PlaceholderAPI]
commands:
 cspy:
  description: "Чекать команды игроков"
  usage: /cspy [player]
 cspycheck:
  description: 'Включено или выключено у вас отслеживание'
  usage: /cspycheck [player]
 cspyreload:
  description: 'Reload CommandSpy plugin'
  usage: /cspyreload