name: CommandSpy
main: me.maxed.cspy.CSpy
description: "Adds to your server Command-Spy system"
version: 1.1
softdepend: [PlaceholderAPI]
commands:
 cspy:
  description: "Toggle command tracking mode"
  usage: /cspy [player]
 cspycheck:
  description: 'Check command tracking mode'
  usage: /cspycheck [player]
 cspyreload:
  description: 'Reload CommandSpy plugin'
  usage: /cspyreload