name: CommandSpy
main: me.maxed.cspy.CSpy
description: "Adds to your server command-tracking system"
version: 1.2.2
api-version: 1.13
author: Memaxed
softdepend: [PlaceholderAPI]
commands:
 cspy:
  description: "Toggle command tracking mode"
  usage: /cspy [player]
  aliases:
  - commandspy
 cspycheck:
  description: 'Check command tracking mode'
  usage: /cspycheck [player]
  aliases:
  - commandspycheck
  - ccheck
 cspyreload:
  description: 'Reload CommandSpy plugin'
  usage: /cspyreload
  aliases:
  - commandspyreload
 chistory:
  description: "Show list of logged commands"
  usage: /chistory <player>
  aliases:
  - chist
  - commands
  - cmds
  