name: CommandSpy
main: me.maxed.cspy.CSpy
description: "Adds to your server command-tracking system"
version: 1.2
api-version: 1.13
author: Memaxed
softdepend: [PlaceholderAPI]
commands:
 cspy:
  description: "Toggle command tracking mode"
  usage: /cspy [player]
 cspycheck:
  description: 'Check command tracking mode'
  usage: /cspycheck [player]
 cspyreload:
  description: 'Reload CommandSpy plugin'
  usage: /cspyreload